---
name: ChatBot_ImageGen
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  iconsax: ^0.0.8
  flutter_spinkit: ^5.1.0
  chat_gpt_flutter: ^1.0.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  flutter_bloc: ^8.1.2
  chat_gpt_sdk: ^2.0.0
  cached_network_image: ^3.2.3
  http: ^0.13.5
  fluttertoast: ^8.1.3
  dio: ^4.0.6
  image_gallery_saver: ^1.7.1
  flutter_riverpod: ^2.2.0
  flutter_side_menu: ^0.3.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  shared_preferences: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
